# documentation: https://pyrodactyl.dev/
# slogan: Pyrodactyl is an open, secure, and scalable servers platform. It's the world's best Pterodactyl panel with incredible performance and unmatched features.
# tags: game, game server, management, panel, minecraft
# logo: svgs/pyrodactyl.png
# port: 80

services:
  pyrodactyl:
    image: 'ghcr.io/pyrohost/pyrodactyl:main'
    volumes:
      -
        type: bind
        source: ./pterodactyl/var
        target: /app/var
        is_directory: true
      -
        type: bind
        source: ./nginx
        target: /etc/nginx/http.d
        is_directory: true
      - 
        type: bind
        source: ./pterodactyl/logs
        target: /app/storage/logs
        is_directory: false
    environment:
      - SERVICE_FQDN_PYRODACTYL=${SERVICE_FQDN_PYRODACTYL}
      
      # Below are Pyrodactyl specific EMV VARS.
      - APP_ENV=production
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_THEME=${APP_THEME:-pterodactyl}
      - APP_TIMEZONE=${APP_TIMEZONE:-UTC}
      - APP_URL=${SERVICE_FQDN_PYRODACTYL}
      - APP_LOCALE=${APP_LOCALE:-en}
      - APP_ENVIRONMENT_ONLY=false

      - DB_CONNECTION=mariadb
      - DB_HOST=${DB_HOST:-database}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-pyrodactyl}
      - DB_USERNAME=${DB_USERNAME:-pyrodactyl}
      - DB_PASSWORD=${SERVICE_PASSWORD_DATABASE}
      
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_USERNAME=${REDIS_USERNAME:-default}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-null}
      - REDIS_PORT=6379

      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis

      - APP_SERVICE_AUTHOR=${APP_SERVICE_AUTHOR:-panel@pyrodactyl.dev}
      
  database:
    image: 'mariadb:10.5'
    environment:
      # Below are MariaDB specific EMV VARS.
      - MARIADB_ROOT_PASSWORD=$DB_PASSWORD
      - MARIADB_DATABASE=$DB_DATABASE
      - MARIADB_USER=$DB_USERNAME
      - MARIADB_PASSWORD=$DB_PASSWORD
    volumes:
      -
        type: bind
        source: ./database
        target: /var/lib/mysql
        is_directory: true

  redis:
    image: 'redis:alpine'
    environment:
      # Below are Redis specific EMV VARS.
      - REDIS_PORT=6379
      - REDIS_USERNAME=$REDIS_USERNAME
      - REDIS_PASSWORD=$REDIS_PASSWORD
    volumes:
      -
        type: bind
        source: ./redis
        target: /data
        is_directory: true
