# documentation: https://pyrodactyl.dev/
# slogan: Pyrodactyl is an open, secure, and scalable servers platform. It's the world's best Pterodactyl panel with incredible performance and unmatched features.
# tags: game, game server, management, panel, minecraft
# logo: svgs/pyrodactyl.png
# port: 8080

services:
  pyrodactyl:
    image: 'ghcr.io/pyrohost/pyrodactyl:main'
    volumes:
      - type: bind
        source: ./app/var/
        target: /pyrodactyl
        is_directory: true
      - type: bind
        source: ./etc/nginx/http.d/
        target: /nginx
        is_directory: true
      - type: bind
        source: ./app/storage/logs
        target: /logs
        is_directory: true
    environment:
      - SERVICE_FQDN_PYRODACTYL=${SERVICE_FQDN_PYRODACTYL}
      
      # Below are Pyrodactyl specific EMV VARS.
      - APP_ENV=production
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_THEME=${APP_THEME:-pterodactyl}
      - APP_TIMEZONE=${APP_TIMEZONE:-UTC}
      - APP_URL=${SERVICE_FQDN_PYRODACTYL}
      - APP_LOCALE=${APP_LOCALE:-en}
      - APP_ENVIRONMENT_ONLY=false

      - DB_CONNECTION=mariadb
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-pyrodactyl}
      - DB_USERNAME=${DB_USERNAME:-pyrodactyl}
      - DB_PASSWORD=${SERVICE_PASSWORD_DATABASE}
      
      - REDIS_HOST=host.docker.internal
      - REDIS_USERNAME=${SERVICE_USER_REDIS}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
      - REDIS_PORT=6379

      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis

      - APP_SERVICE_AUTHOR=${APP_SERVICE_AUTHOR:-panel@pyrodactyl.dev}
      
  database:
    image: 'mariadb:10.5'
    environment:
      # Below are MariaDB specific EMV VARS.
      - MARIADB_ROOT_PASSWORD=${SERVICE_PASSWORD_DATABASE}
      - MARIADB_DATABASE=${DB_DATABASE:-pyrodactyl}
      - MARIADB_USER=${DB_USERNAME:-pyrodactyl}
      - MARIADB_PASSWORD=${SERVICE_PASSWORD_DATABASE}
    volumes:
      - type: bind
        source: ./var/lib/mysql
        target: /database
        is_directory: true

  redis:
    image: 'redis:alpine'
    environment:
      # Below are Redis specific EMV VARS.
      - REDIS_PORT=6379
      - REDIS_USERNAME=${SERVICE_USER_REDIS}
      - REDIS_PASSWORD=${SERVICE_PASSWORD_REDIS}
    volumes:
      - type: bind
        source: ./redis
        target: /redis
        is_directory: true
